#Danny Radosevich
#For Loops example
#COSC1101
towns = ["Cheyenne",
"Casper",
"Gillette",
"Laramie",
"Rock Springs",
"Sheridan",
"Evanston",
"Green River",
"Jackson",
"Riverton",
"Cody",
"Rawlins",
"Lander",
"Powell",
"Ranchettes",
"Douglas",
"Torrington",
"Worland",
"South Greeley",
"Buffalo",
"Mills",
"Fox Farm-College",
"Wheatland",
"Newcastle",
"Warren AFB",
"Bar Nunn",
"Evansville",
"North Rock Springs",
"Thermopolis",
"Kemmerer",
"Glenrock",
"Lovell",
"Pinedale",
"Afton",
"Lyman",
"Hoback",
"South Park",
"Star Valley Ranch",
"Fort Washakie",
"Saratoga",
"Arapahoe",
"Greybull",
"Ethete",
"Wright",
"Lusk",
"Wilson",
"Rafter J Ranch",
"Moose Wilson Road",
"Mountain View town",
"Alpine",
"Basin",
"Sleepy Hollow",
"Pine Bluffs",
"Guernsey",
"Ranchester",
"Sundance",
"Hartrandt",
"Clearview Acres",
"Red Butte",
"Moorcroft and Casper Mountain",
"Powder Horn",
"Dubois",
"Upton",
"Grover",
"Osmond and Dayton",
"Marbleton",
"Story",
"Cowley",
"Purple Sage",
"Teton Village",
"Vista West",
"Hanna",
"James Town",
"Auburn",
"Byron",
"Diamondville",
"Bear River",
"Bedford",
"Pine Haven",
"Cokeville",
"Shoshoni",
"Lucerne",
"Encampment",
"Hudson",
"Ralston",
"Rolling Hills",
"Baggs",
"La Barge",
"Lingle",
"Thayne",
"Big Horn",
"LaGrange",
"Sinclair",
"Big Piney",
"Burns",
"Parkman",
"Smoot",
"Boulder Flats",
"Burlington",
"Urie",
"Hulett",
"Meeteetse",
"Nordic",
"Alta",
"Centennial",
"Midwest",
"Kaycee",
"Reliance",
"Ten Sleep",
"Medicine Bow",
"Glendo",
"Pavillion and East Thermopolis",
"Johnstown",
"Rock River",
"Farson",
"Fort Laramie",
"Freedom",
"Wamsutter",
"Y-O Ranch and Homa Hills",
"Garland",
"Kelly",
"Superior",
"Carpenter",
"Chugwater",
"Albin",
"Taylor",
"Alpine Northwest",
"Deaver",
"Edgerton",
"Elk Mountain",
"Frannie",
"Lakeview North",
"Woods Landing-Jelm",
"Yoder",
"Eden",
"Crowheart",
"Bessemer Bend",
"Arrowhead Springs",
"Clearmont",
"Brookhurst",
"Daniel",
"Fort Bridger and Hyattville",
"Cora",
"Whiting",
"Turnerville, Manville, and Granger",
"Shell",
"Manderson",
"Orin",
"Mammoth",
"Fairview",
"Dixon",
"Kirby",
"Esterbrook",
"Meadow Acres",
"Washam, Bairoil, and Hartville",
"Hill View Heights and McKinnon",
"Riverside and Opal",
"Point of Rocks",
"Bondurant and Slater",
"Osage",
"Albany and Alpine Northeast",
"Chugcreek",
"Robertson",
"Fontenelle",
"Alcova",
"Little America",
"Lance Creek",
"Arvada",
"Boulder, Mountain View, and Ryan Park",
"Van Tassell and Jeffrey City",
"Hawk Springs",
"Lonetree",
"Fox Park",
"El Rancho",
"Lost Springs"]

for town in towns:
    print(town)

for i in range(len(towns)):
    print(f"{i}:\t{towns[i]}")

for i in range(1,100):
    if i%2 == 0:
        print(f"{i} is even")
    else:
        print(f"{i} is odd")